name: Deploy dekorsever

on:
  push:
    branches: [main]

jobs:
  
  #test: #Название первой задачи
    #runs-on: ubuntu-latest #На какой системе будет запущена задача. ubuntu-latest система на которой работает GitHub
    #steps: #Шаги которые будут выполненны последовательно один за другим
      #- uses: actions/checkout@v4 #Cкачивает ваш код из репозитория на виртуальную машину (Обязательно)
      #- run: npx html-validate "**/*.html" #Ищем все html файлы и проверяем ошибки
      #- run: echo "Checked complite!" #Выводим сообщение

  check-php: # Проверка PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: find . -name "*.php" -exec php -l {} \;

  deploy:
    runs-on: ubuntu-latest
    #needs: test  #Деплой запустится только если test прошел успешно
    needs: check-php  # Деплой запустится только если check-php прошел успешно
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEKORSEVER_HOST }}
          username: ${{ secrets.DEKORSEVER_USER }}
          key: ${{ secrets.DEKORSEVER_KEY }}
          script: |
            #Переключаемся в нужную папку
            cd ~/dekorsever/public_html/wp-content/themes/dekorsever
            
            # Клонируем репозиторий в папку (только для первой выгрузки!!!)
            #git clone https://github.com/site100ru/dekorsever.git .
            
            # Клонируем репозиторий в папку
            # git pull
            
            #Если кто то изменил файлы на сервере минуя GitHub, перезаписываем версию на сервере из GitHub
            git reset --hard HEAD
            git pull origin main